name: Frontend CI - DEBUG

on:
  push:
    branches:
      - 'feature/frontend-ci-v2' # Ограничиваем запуск только нашей веткой
  pull_request:
    branches:
      - 'main'

jobs:
  investigate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List all files recursively
        # Эта команда - наша "видеокамера".
        # ls -R покажет нам КАЖДЫЙ файл и КАЖДУЮ папку в проекте.
        run: ls -R